### ISSUE TITLE
Can't find entry by site handle

### ISSUE THREAD

**Issue by embyte-software** [statamic/importer#102]
### Bug description

In the findOrCreateEntry function of ImportItemJob.php, there is a where clause filtering by 'locale' using `$site->handle()`. However, in my case, the site locale differs from the site handle, which causes the query to not find the existing entry. As a result, a new entry is created instead of updating the existing one.

Here’s the original code:

```php
$entry = Entry::query()
            ->where('locale', $site->handle())
            ->where('collection', $collection->handle())
            ->where($this->import->get('unique_field'), $data[$this->import->get('unique_field')])
            ->first();
```
After changing 'locale' to 'site', everything works as expected:
```php
$entry = Entry::query()
            ->where('site', $site->handle())
            ->where('collection', $collection->handle())
            ->where($this->import->get('unique_field'), $data[$this->import->get('unique_field')])
            ->first();
```

**Question:**
Is this the intended behavior? Should 'locale' always match the site handle, or is 'site' the correct field to query in this context?

### How to reproduce

- Create a new multisite setup in Statamic, ensuring that each site has a locale that is different from its handle.
- Install the Statamic Importer addon.
- Configure an import that targets a collection
- Set the import strategy to create new items and update existing items based on a unique field.
- Run the import with data that matches existing entries (based on the unique field).
- Observe that instead of updating existing entries, new entries are created.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Wijmarbouwmachines
Laravel Version: 11.44.1
PHP Version: 8.3.20
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: wijmarbouwmachines.test
Maintenance Mode: OFF
Timezone: UTC
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR, EUR, EUR
Gateways: Rabo Smart Pay, Op rekening
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Pakketverzending, Afhalen
Tax Engine: App\Engines\TaxEngine

Livewire
Livewire: v3.6.1

Statamic
Addons: 9
Sites: 3 (Wijmarbouwmachines, Heater Shop, Eibenstock Shop)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.51.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.14.0
duncanmcclean/simple-commerce: 7.8.1
jacksleight/statamic-bard-texstyle: 3.4.1
jonassiewertsen/statamic-livewire: 3.8.1
rias/statamic-redirect: 3.9.3
statamic-rad-pack/runway: 7.14.0
statamic/eloquent-driver: 4.20.2
statamic/importer: 1.7.5
withcandour/aardvark-seo: 5.0.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
