### ISSUE TITLE
XML import mapping interface shows no fields (CSV works)

### ISSUE THREAD

**Issue by wortberge** [statamic/importer#103]
### Bug description

When uploading a valid XML file in the Importer utility, the blueprint fields are correctly detected and listed. However, the mapping dropdowns (for assigning file fields to blueprint fields) remain completely empty.
The same dataset converted to CSV works without issues — mapping options appear and import runs successfully.

### How to reproduce

1. Install and configure Statamic and the statamic/importer addon.
2. Ensure job_batches table exists via php artisan queue:batches-table and php artisan migrate.
3. Upload a minimal, valid XML file (root element: <vacancies>, items: <vacancy>, children: <title>, <url>, etc.)
5. Proceed through import setup: At the field mapping step: the blueprint fields appear, but the mapping sources from the file remain empty.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: ALPMA Career
Laravel Version: 12.14.1
PHP Version: 8.3.16
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: alpma-jobs.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Locales
Installed: cs, da, de, en, nb, nl, nn
LaravelLang\Actions\Plugin: 1.10.1
LaravelLang\Attributes\Plugin: 2.13.4
LaravelLang\HttpStatuses\Plugin: 3.10.3
LaravelLang\Lang\Plugin: 15.20.2
LaravelLang\MoonShine\Plugin: INCORRECT
LaravelLang\StarterKits\Plugin: 1.3.8
Locales Version: 2.10.0
Protected: en
Publisher Version: 16.6.0

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.55.0 PRO

Statamic Addons
statamic/importer: 1.8.1
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-commands: 9.0.1
studio1902/statamic-peak-seo: 8.23.0
studio1902/statamic-peak-tools: 7.2.0
```

### Additional details

**Expected Behavior:**

All XML child elements inside <vacancy> should be parsed as mappable fields.

**Actual Behavior:**

No source fields from the uploaded XML are shown in the mapping interface, despite them being valid and present.

**Tested:**

- XML with <vacancies><vacancy>…</vacancy></vacancies> (5 items)
- All fields flat, no nesting
- Charset: UTF-8
- Same data works via CSV (confirmed)
- Blueprint includes text, textarea, bard, date, slug, etc.

`<vacancies>
  <vacancy>
    <id>abc123</id>
    <title>Test Title</title>
    <url>https://example.com/job</url>
    <alpma_profile>This is some text.</alpma_profile>
    <applicant_responsibilities><![CDATA[<ul><li>Item</li></ul>]]></applicant_responsibilities>
  </vacancy>
</vacancies>`

- The XML seems to be parsed, since no error is shown.
- config/app.php uses APP_DEBUG=true, but logs show no error or exception.
- Looks like the XML file is not fully scanned for field keys, or the parser does not pass the field structure through to the UI.
- The issue occurs even with clean XML and known field names.
