### ISSUE TITLE
Importer doesn't use process source images setting

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#14]
### Bug description

Importer doesn't use process source images setting

<img width="935" alt="Screenshot 2024-10-29 at 19 32 10" src="https://github.com/user-attachments/assets/6d6c87e6-6751-4bc6-8703-bb8a7feddb3e">

If I import images, they aren't resized based on the settings here
`/cp/asset-containers/assets/edit`

### How to reproduce

- Set a `max_upload_size` in `/cp/asset-containers/assets/edit`
- Import an image you know is bigger than the  `max_upload_size`
- The image isn't resized.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: vocal.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.0.2
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
