### ISSUE TITLE
Error when importing Bard field in imported fieldset

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#17]
### Bug description

I've created a blueprint that's using a prefixed bard fieldset. When I try to import I get this error
```
local.ERROR: Undefined array key "resources_bard_basic"
```

I've removed the prefix, still using a fieldset and I get a similar error
```
local.ERROR: Undefined array key "bard_basic"
```

However, if I don't use a `fieldset`, just a regualr `bard` fieldtype... it works.

Other fieldsets, like my `author` works.

### How to reproduce

- Use a bard fieldset in a blueprint
- Try to import content into that 
-  local.ERROR: Undefined array key

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.29.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: vocal.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.0.2
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
