### ISSUE TITLE
Unable to import CSV file. "The chosen collection is not available on this site"

### ISSUE THREAD

**Issue by mboisvertdupras** [statamic/importer#25]
### Bug description

I'm trying to import a csv file to create some entries on a multi-site install but no matter what Collection/Site I choose I get a "The chosen collection is not available on this site." error. I'm also using the Eloquent driver if that changes anything.

### How to reproduce

1. Create a multi-site and setup Collections to use the Eloquent driver
2. Setup 2 sites (we have an english and a french site)
3. Try to import the attached csv into entries of a collection that uses the Eloquent driver

[CSV File](https://github.com/user-attachments/files/17636269/fillactive.csv)

### Environment

```yaml
Environment
Application Name: Fillactive
Laravel Version: 11.28.1
PHP Version: 8.3.13
Composer Version: 2.7.9
Environment: local
Debug Mode: ENABLED
URL: fillactive.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 2 (Français, Anglais)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.32.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.15.2
statamic/importer: 1.1.1
statamic/seo-pro: 6.3.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
