### ISSUE TITLE
Undefined array key "source" on XML type

### ISSUE THREAD

**Issue by JMRhodes** [statamic/importer#38]
### Bug description

Seeing an issue when trying to Save or Run an import with a WordPress XML export file. This appears to be expecting the `source` config for the `csv_delimiter`, but that doesn't get set with an XML type. 

If I revert to a version prior to `v1.2.0` I am no longer experiencing this error.

I was also able to get around the issue in `1.4.0` by directly modifying the expected config value at `ImportController.php:175`, changing the source key assignment to `$values['source'] ?? []`:
```
$import
    ->name($request->name)
    ->config($import->config()->merge([
        'type' => $type,
        'path' => $path,
        'destination' => collect($values['destination'])->filter()->all(),
        'strategy' => $values['strategy'],
        'source' => $values['source'] ?? [],
        'mappings' => $values['mappings'],
        'unique_field' => $values['unique_field'],
    ]));
```
**OR**

I can also modify the importer YML file directly to add the expected source config as an empty object, which is otherwise not being set:
```
config:
    source: { }
```

### How to reproduce

Create an import with an XML file exported from a WordPress instance. When mapping the fields, you are unable to Save or "Save & Run" the import, due to the error: `Undefined array key "source"`.

### Logs

```shell
[2024-11-20 16:34:51] local.ERROR: Undefined array key "source" {"userId":"7adfd44e-08e0-44bd-a7cb-6970669914bd","exception":"[object] (ErrorException(code: 0): Undefined array key \"source\" at /app/vendor/statamic/importer/src/Http/Controllers/ImportController.php:175)
```

### Environment

```yaml
Environment
Application Name: Inside.Statamic
Laravel Version: 11.33.2
PHP Version: 8.3.13
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: insidestatamic.lndo.site
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.38.1 PRO

Statamic Addons
statamic/importer: 1.4.0
```
