### ISSUE TITLE
Argument #1 ($handle) must be of type string, null given

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#52]
### Bug description

The recent updates appear to have fixed many of the problems I was having with the importer addon. I've tried to remove the additional config for extending transformers in `AppServiceProvider.php`

I've commented all but one `App\ImportTransformer` out. However, when I try to remove all the code referencing `ImportTransformers` I get an error?

```php
namespace App\Providers;

use App\ImportTransformers\{
    // ResourcesText,
    // ArchiveTransformer,
    // ResourcesSlug,
    // ResourcesBard,
    ResourcesAssets
    // Date
};
use Illuminate\Support\ServiceProvider;
use Statamic\Importer\Importer;
use Statamic\Statamic;
use Statamic\Facades\CP\Nav;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        \Statamic\Tags\Svg::disableSanitization();

        Statamic::vite('app', [
            'resources/js/cp.js',
            'resources/css/cp.css',
        ]);

        Nav::extend(function ($nav) {
            $nav->remove('Top Level', 'Dashboard');
        });

        Statamic::booted(function () {
            $this->registerImporterTransformers();
        });
    }

    private function registerImporterTransformers(): void
    {
        $transformers = [
            // 'text' => ResourcesText::class,
            // 'toggle' => ArchiveTransformer::class,
            // 'slug' => ResourcesSlug::class,
            // 'bard' => ResourcesBard::class,
            'assets' => ResourcesAssets::class
            // 'date' => Date::class,
        ];

        foreach ($transformers as $key => $class) {
            Importer::registerTransformer($key, $class);
        }
    }
}
```
This is my current `AppServiceProvider.php` file

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Statamic\Statamic;
use Statamic\Facades\CP\Nav;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        \Statamic\Tags\Svg::disableSanitization();

        Statamic::vite('app', [
            'resources/js/cp.js',
            'resources/css/cp.css',
        ]);

        Nav::extend(function ($nav) {
            $nav->remove('Top Level', 'Dashboard');
        });

       
    }

    
}
```
When using the file above, I get this error? There's no reference to my transformers.
<img width="1413" alt="Screenshot 2024-11-29 at 16 36 54" src="https://github.com/user-attachments/assets/f5d6ec53-070c-4a93-adf7-00ee5c012d65">

Is there anything else I need to remove to stop Statamic thinking I'm using my own transformers? Or is there anything you can think of that might be causing this? I've used `php artisan optimize:clear`.

### How to reproduce

I've not added any content to asset fields in the importer, so I'm not sure why this is failing?

### Logs

```shell
local.ERROR: Statamic\Stache\Repositories\AssetContainerRepository::findByHandle(): Argument #1 ($handle) must be of type string, null given, called in /Users/stephenmeehan/Repositories/vocal/vendor/statamic/cms/src/Stache/Repositories/AssetContainerRepository.php on line 29 {"userId":"b15f938b-884b-47c5-be06-8d48967da74d","exception":"[object] (TypeError(code: 0): Statamic\\Stache\\Repositories\\AssetContainerRepository::findByHandle(): Argument #1 ($handle) must be of type string, null given, called in /Users/stephenmeehan/Repositories/vocal/vendor/statamic/cms/src/Stache/Repositories/AssetContainerRepository.php on line 29 at /Users/stephenmeehan/Repositories/vocal/vendor/statamic/cms/src/Stache/Repositories/AssetContainerRepository.php:32)
```

### Environment

```yaml
Environment
Application Name: Vocal
Laravel Version: 11.34.2
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: vocal.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.5.0
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
