### ISSUE TITLE
Imported fieldset in blueprint causes undefined array index error

### ISSUE THREAD

**Issue by Michael-Stokoe** [statamic/importer#54]
### Bug description

My blueprint uses an imported fieldset via `import: primary_content`.

When attempting to import content into this field, the importer throws the following exception:

```
ErrorException: Undefined array key "primary_content" in /Users/michaelstokoe/projects/xxxxxxx-xxxxxx/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1792
```

### How to reproduce

Import entries using a blueprint that uses an imported fieldset.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.25
PHP Version: 8.3.12
Composer Version: 2.8.1
Environment: local
Debug Mode: ENABLED
URL: xxxxxxxxxxxxx.test # Hidden for privacy.
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: array
Database: mysql
Logs: stack / single, bugsnag
Mail: smtp
Queue: redis
Scout: algolia
Session: file

Statamic
Addons: 4
Sites: 3 (English, Japanese, Chinese)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.40.0 PRO

Statamic Addons
rias/statamic-data-import: 1.5.0
statamic/eloquent-driver: 4.15.2
statamic/importer: 1.0.2
statamic/seo-pro: 6.1.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: file
Terms: file
Tokens: eloquent
```
```


### Additional details

_No response_
