### ISSUE TITLE
type: grid not showing in importer?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#60]
### Bug description

I've added a `type: grid` to my blueprint, but it's not listed in the importer?

### How to reproduce

Add `type: grid` to a blueprint, try to import into a collection that uses the blueprint. The `type: grid` isn't listed?

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: vocal.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.5.1
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
