### ISSUE TITLE
Importer restores bard buttons to default?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#61]
### Bug description

My bard fieldtype looks like this before I run import

```
            handle: hero_intro
            field:
              buttons:
                - bold
                - italic
                - anchor
              inline: break
              fullscreen: false
              allow_source: false
              remove_empty_nodes: false
              type: bard
              display: 'Hero Intro'
              container: assets
```
after running an import it changes to this?

```
            handle: hero_intro
            field:
              buttons:
                - h1
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
                - horizontalrule
                - codeblock
                - underline
                - superscript
              inline: break
              fullscreen: false
              allow_source: false
              remove_empty_nodes: false
              type: bard
              display: 'Hero Intro'
              container: assets
```
This happens on all my bard field types. Even ones pulled in as fieldsets.

### How to reproduce

Create a bard fieldtype, edit the buttons. Run an import. The edits to the bard fieldtype will be reset.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: vocal.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.5.1
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
