### ISSUE TITLE
Bard Import Issue with HTML Content from CSV

### ISSUE THREAD

**Issue by borkk85** [statamic/importer#62]
### Bug description

I’m encountering an issue when importing content into Statamic’s Bard field. The content originates from a WYSIWYG rich text editor in WordPress and is provided as HTML in a CSV file. I am using the WP All Export plugin to export the posts content. 

There is nothing out of the ordinary or custom in the WYSIWYG rich text editor, just paragraphs, list items, headings and some images. 

Here's a breakdown of the situation:

The content imports successfully into the Bard field, however it is non-editable in the post control panel.
I attempted to clean and transform the data during import using a custom transformer and Gutenberg hook, but it didn’t resolve the issue.

### How to reproduce

I did attempt to clean the content. Hooked into core/html blocks and tried transforming the content.
Also I have all the buttons enabled to show in the toolbar, however after the import they default to the currently provided blueprint

```
public function transform($value)
    {
        if (empty($value)) {
            return null;
        }

        $cleanContent = str_replace("\x00", '', trim($value));

        $html = strip_tags($cleanContent, '<p><h2><h3><ul><li><strong><em>');

        return [
            [
                'type' => 'text',
                'content' => [['type' => 'text', 'text' => $html]],
            ]
        ];
    }

  public function boot(): void
    {        

        Gutenberg::hook('core/html', function ($payload, $next) {
            $html = $payload['attrs']['content'] ?? '';
            $transformer = new Transformer();

            return [
                'type' => 'bard',
                'content' => $transformer->transform($html),
            ];
        });
    
   }
```

My posts blueprint

```
 handle: content
            field:
              buttons:
                - h1
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
                - horizontalrule
                - codeblock
                - underline
                - superscript
              remove_empty_nodes: trim
              type: bard
              display: Content
              localizable: false
              container: assets
              smart_typography: true
              antlers: true
              link_noopener: true
              link_noreferrer: true
              target_blank: true
              link_collections:
                - posts
              previews: false
              sets:
                content:
                  display: Content
```

### Logs

```shell
[2024-12-18 09:37:54] local.ERROR: Debugbar exception: Strings with null bytes cannot be escaped. Use the binary escape option.  
[2024-12-18 10:08:06] local.ERROR: Debugbar exception: Strings with null bytes cannot be escaped. Use the binary escape option.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.35.1
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: tools4ever.nl.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 2 (EN, NL)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
statamic/importer: 1.2.0
```
