### ISSUE TITLE
Importing Bard content changes active toolbar buttons

### ISSUE THREAD

**Issue by carstenjaksch** [statamic/importer#72]
### Bug description

After an import of Bard content, all my Bard fields have their active toolbar buttons changed.

The new active buttons correspond with this list: https://github.com/statamic/importer/blob/main/src/Transformers/BardTransformer.php#L68

### How to reproduce

Import Bard content, the toolbar buttons of the target fields change.

### Environment

```yaml
Environment
Application Name: Gutachterix
Laravel Version: 11.36.1
PHP Version: 8.3.15
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: gutachterix.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: reverb
Cache: file
Database: sqlite
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 2 (Gutachterix, Clever-Immo)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.4.1
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/collaboration: 1.0.0
statamic/importer: 1.6.0
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.13.0
studio1902/statamic-peak-seo: 8.18.0
studio1902/statamic-peak-tools: 6.6.0
```
