### ISSUE TITLE
Importing categories issue

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#82]
### Bug description

When using the importer to import categories, they're imported like this

```
categories:
  - 'categories::cinema'
```

When I manually add and save a category, it's formatted differently

```
categories:
  - cinema
```

The imported categories show up in the entry
<img width="317" alt="Screenshot 2025-01-10 at 10 14 56" src="https://github.com/user-attachments/assets/312806b8-4ce0-4bf6-a088-9acd8829271c" />

But they're not listed on the entry listing page
<img width="592" alt="Screenshot 2025-01-10 at 10 15 32" src="https://github.com/user-attachments/assets/cbb7a7fb-ef19-49d7-8df2-636ee002b24c" />

And they're not working in my templates.

### How to reproduce

Import this sample CSV
[Import_ Case Studies - Sheet1 (2).csv](https://github.com/user-attachments/files/18375316/Import_.Case.Studies.-.Sheet1.2.csv)

### Environment

```yaml
Environment
Application Name: Bones
Laravel Version: 11.37.0
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: bones-stater.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en_GB

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.1 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.7.1
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
