### ISSUE TITLE
BardTransformer fails to handle deep child image elements when performing asset transforming

### ISSUE THREAD

**Issue by tdondich** [statamic/importer#84]
### Bug description

When importing html content, the html may contain nested html elements that are multiple levels deep that are image element.

The current BardTransformer assumes there is not nested html elements when working with the AssetTransformer. 

As such, no deep image elements are evaluated for the need of Asset transformation and are ignored when they should be processed.

### How to reproduce

Use this example import xml.

```xml
<?xml version="1.0" encoding="UTF-8"?>

<rss version="2.0"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
>

    <channel>

        <item>
            <title><![CDATA[Test Item with Nested IMG Element]]></title>
            <content:encoded><![CDATA[This is a simple example where nested img element will not be processed.

<p><img src="https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png" alt="Test image" /></p>

]]></content:encoded>
        </item>
    </channel>
</rss>
```

Note that the img element is nested inside a paragraph element.  Common in html content.  This can also be replicated if the image was on it's own line with empty lines above and the Replace double line-breaks with <p> tags was enabled.

- Create a test collection.
- Modify test collection blueprint to have content field be a bard type with an associated asset container.
- Attempt to import the xml using an importer.  Ensure mapping the bard field to the content:encoded value.  Ensure configuring asset downloading and configure the Base URL to be https://github.githubassets.com/assets

- Review created entry.  Note the image element does not link to an asset and no asset was created in the related asset container.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: DNS Spy
Laravel Version: 10.48.27
PHP Version: 8.2.26
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: mysql
Logs: stack / daily, sentry
Mail: ses
Queue: sync
Session: file

Filament
Blade Icons: NOT CACHED
Packages: filament, forms, notifications, support, tables
Panel Components: NOT CACHED
Version: v3.2.130
Views: NOT PUBLISHED

Livewire
Livewire: v3.5.18

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.11.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.19.1
statamic/importer: 1.7.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
