### ISSUE TITLE
Fieldtype [import_mappings] not found.

### ISSUE THREAD

**Issue by DuyTr** [statamic/importer#86]
### Bug description

[dealers_update.csv](https://github.com/user-attachments/files/18713624/dealers_update.csv)

This is an example of the csv file that I use. 

### How to reproduce

I run into this error when trying to create a new import. After entering all the information (data type is Entries), this happens after clicking "Save & Continue". 

I also see the error when clicking on Import in the "Recent Imports" section.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Kartners
Laravel Version: 11.22.0
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.24.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.1
doefom/statamic-export: 0.4.0
duncanmcclean/static-cache-manager: 4.0.0
jonassiewertsen/statamic-livewire: 3.6.0
statamic/importer: 1.2.0
```
