### ISSUE TITLE
User import shows no blueprint

### ISSUE THREAD

**Issue by wm-simon** [statamic/importer#88]
### Bug description

When I select the data type to users, there is no blueprint listed in the select field. With other types there is no problem and the blueprints are shown. The user blueprint exists in the site tree.

![Image](https://github.com/user-attachments/assets/b00d2ab1-6496-4b84-ae54-1ec2ae1769ef)

![Image](https://github.com/user-attachments/assets/08aee7f0-cf10-403f-90da-830701786094)

![Image](https://github.com/user-attachments/assets/e3f88e1f-c253-4c45-81d1-6097445193cd)

### How to reproduce

Try to import users.

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 11.42.1
PHP Version: 8.3.7
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.20

Statamic
Addons: 14
Sites: 3 (Deutsch, English, Französisch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
aerni/livewire-forms: 9.5.0
appswithlove/statamic-one-click-content-translation: 5.2.3
ddm-studio/cookie-byte: 1.5.4
insight-media/statamic-pdf-thumbnailer: 1.0.1
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
marcorieser/statamic-instagram: 1.1.0
marcorieser/statamic-livewire: 3.9.0
mitydigital/statamic-google-fonts: 2.0.0
reachweb/locale-lander: 3.0.0
rias/statamic-redirect: 3.9.3
ryanmitchell/statamic-translation-manager: 2.0.0
statamic/importer: 1.7.3
stillat/relationships: 2.2.1
```
