### ISSUE TITLE
Migration warning even if database exists

### ISSUE THREAD

**Issue by mbs-arran-baker** [statamic/importer#90]
### Bug description

Keep getting the migration warning even though a database exists. 

`Please run your migrations.
In order to keep track of import progress, the importer uses Laravel's Job Batching feature. It uses a job_batches table in your database to store information about batches. Before you can run the importer, you will need to run the php artisan migrate command.`

We have migrated users to the database so unsure if this is causing a problem.

### How to reproduce

We have migrated users to the database so unsure if this is causing a problem.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name:  Support
Laravel Version: 10.48.25
PHP Version: 8.3.17
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: support.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.48.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.2
jacksleight/statamic-bard-texstyle: 3.4.1
statamic/importer: 1.7.4
statamic/seo-pro: 6.5.0
```
