### ISSUE TITLE
SQLite error: "too many SQL variables" when importing large datasets

### ISSUE THREAD

**Issue by pixelastronauts** [statamic/importer#96]
### Bug description

I just ran into an issue with the Statamic Importer when trying to process a larger CSV file. The importer crashes with an SQLite error:

```[2025-04-02 15:47:18] local.ERROR: SQLSTATE[HY000]: General error: 1 too many SQL variables (Connection: sqlite, SQL: insert into "jobs" ("attempts", "available_at", ...```

### How to reproduce

**Steps to reproduce**

1. Set up a Statamic site with SQLite
2. Create a XML import with a large number of rows (in my case around 2500 rows)
3. Run the import process
4. Import fails with the SQLite "too many SQL variables" error

### Logs

```shell
[2025-04-02 15:47:18] local.ERROR: SQLSTATE[HY000]: General error: 1 too many SQL variables (Connection: sqlite, SQL: insert into "jobs" ("attempts", "available_at", ...
```

### Environment

```yaml
Environment
Application Name: Voetbal
Laravel Version: 11.41.3
PHP Version: 8.3.17
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.1 PRO

Statamic Addons
doefom/statamic-table-of-contents: 1.2.5
statamic/importer: 1.8.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-tools: 6.7.1
```

### Additional details

Looking at the code, it seems the Importer::run() method is trying to create a job batch with all items at once. SQLite has a limit on the number of variables that can be used in a single query, and this limit is being exceeded when processing large datasets.

I think the importer should handle large datasets by chunking the items into smaller batches. Something like:

```
// Instead of the current implementation
$chunks = $items->chunk(500); // Or some reasonable size

foreach ($chunks as $chunk) {
    Bus::batch($chunk->map(fn (array $item) => new ImportItemJob($import, $item)))
        // ... rest of the batch setup
        ->dispatch();
}
```

This would allow the importer to process large datasets while staying within SQLite's limitations.

I'm happy to submit a PR with the fix if the team agrees with this approach.
